global:
  scrape_interval:     60s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.

alerting:
  alertmanagers:
  - static_configs:
    - targets:

rule_files:

scrape_configs:
  - job_name: 'prometheus_local'
    static_configs:
    - targets: ['localhost:9090']
  - job_name: 'ESXI_Hosts'
    static_configs:
    - targets: ['172.17.0.2:9512']
      labels:
        alias: esx01
    - targets: ['172.17.0.3:9512']
      labels:
        alias: esx02
    - targets: ['172.17.0.4:9512']
      labels:
        alias: esx03



